[workspace]
members = [
  "crates/vino-codec",
  "crates/vino-entity",
  "crates/vino-provider",
  "crates/vino-entity",
  "crates/vino-transport",
  "crates/vino-types",
  "crates/vino-macros",
  "crates/vino-packet",
]
