unstable_features = true
tab_spaces = 2
max_width = 120
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
edition = "2021"
imports_indent = "Block"
imports_granularity = "Module"
imports_layout = "HorizontalVertical"
group_imports = "StdExternalCrate"
trailing_comma = "Vertical"
trailing_semicolon = true
