[package]
name = "wasmflow-output"
version = "0.9.0"
edition = "2021"
license = "BSD-3-Clause"
description = "SDK for native and WASM Vino components"
documentation = "https://docs.vino.dev"
keywords = ["wasm", "vino", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
v1 = []
signatures = []


[dependencies]
tokio-stream = { version = "0.1", features = [] }
wasmflow-packet = { path = "../wasmflow-packet", version = "0.9.0" }
wasmflow-streams = { path = "../wasmflow-streams", version = "0.9.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
vino-transport = { path = "../vino-transport", version = "0.9.0", features = [
  "async",
] }

[dev-dependencies]
