[package]
name = "vino-entity"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vino-macros = { path="../vino-macros" }
serde = { version="1.0.118", features=["derive"] }
thiserror = "1.0.25"
url = "2.2.2"

[dev-dependencies]
pretty_assertions = "0.7.2"
