[package]
name = "wasmflow-collection-link"
version = "0.9.0"
edition = "2021"
license = "BSD-3-Clause"
description = "SDK for native and WASM Vino components"
documentation = "https://docs.vino.dev"
keywords = ["wasm", "vino", "actor", "flow"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []


[dependencies]
wasmflow-component = { path = "../wasmflow-component", version = "0.9.0" }
wasmflow-packet = { path = "../wasmflow-packet", version = "0.9.0" }
wasmflow-output = { path = "../wasmflow-output", version = "0.9.0" }
wasmflow-entity = { path = "../wasmflow-entity", version = "0.9.0" }
wasmflow-codec = { path = "../wasmflow-codec", version = "0.9.0" }

serde = { version = "1.0", features = ["derive"] }
tokio-stream = { version = "0.1", features = [] }

[dev-dependencies]
env_logger = "0.9"
test-log = "0.2.8"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
anyhow = "1.0"
wasmflow-packet = { path = "../wasmflow-packet", version = "0.9.0", features = [] }
