[package]
name = "vino-types"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }

[dev-dependencies]
