[package]
name = "vino-types"
version = "0.7.0"
edition = "2018"
license = "BSD-3-Clause"
description = "Types used by the Vino tool chain"
documentation = "https://docs.vino.dev"
keywords = ["types", "vino"]
categories = []
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
log = "0.4.14"
serde_json = "1.0"

[dev-dependencies]
anyhow = "1.0.44"
test-env-log = "0.2.7"
env_logger = "0.9"
