[package]
name = "vino-transport"
version = "0.7.0"
edition = "2018"
license = "BSD-3-Clause"
description = "Transport layer for Vino packets"
documentation = "https://docs.vino.dev"
keywords = ["serde", "vino", "packet", "transport"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["stream", "async", "json", "raw"]
wasm = []
stream = ["tokio-stream"]
async = ["tokio"]
json = ["serde_json"]
raw = ["serde-value"]

[dependencies]
vino-packet = { path = "../vino-packet", version = "0.7.0" }
vino-codec = { path = "../vino-codec", version = "0.7.0" }
serde = { version = "1.0.118", features = ["derive"] }
thiserror = "1.0.25"
log = "0.4.14"

# raw
serde-value = { version = "0.7.0", optional = true }

# json
serde_json = { version = "1.0.64", optional = true }

# stream
tokio-stream = { version = "0.1.6", optional = true }

# async
tokio = { version = "1.4.0", features = [], optional = true }

[dev-dependencies]
test-env-log = "0.2.7"
env_logger = "0.9.0"
log = "0.4"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "macros"] }
