[package]
name = "vino-transport"
version = "0.1.0"
authors = ["Jarrod Overson <jsoverson@gmail.com>"]
edition = "2018"
license = "Apache-2.0"

[dependencies]
vino-component = { path = "../vino-component" }
vino-codec = { path = "../vino-codec" }
serde = { version = "1.0.118", features = ["derive"] }
serde_json = "1.0.64"
rmp-serde = "0.15.4"
thiserror = "1.0.25"
log = "0.4.14"
serde-value = "0.7.0"
tokio-stream = { version = "0.1.6" }
tokio = { version = "1.4.0", features = [] }
lazy_static = "1.4.0"

[dev-dependencies]
test-env-log = "0.2.7"
env_logger = "0.9.0"
log = "0.4"
tokio = { version = "1.4.0", features = ["rt-multi-thread", "macros"] }
