[package]
name = "vino-transport"
version = "0.9.0"
edition = "2021"
license = "BSD-3-Clause"
description = "Transport layer for Vino packets"
documentation = "https://docs.vino.dev"
keywords = ["serde", "vino", "packet", "transport"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]
repository = "https://github.com/vinodotdev/vino-sdk"
homepage = "https://docs.vino.dev"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = []
all = ["async", "json", "raw"]
wasm = []
async = ["tokio", "tokio-stream", "parking_lot"]
json = ["serde_json"]
raw = ["serde-value"]

[dependencies]
vino-packet = { path = "../vino-packet", version = "0.9.0", features = [
  "v0",
  "v1",
] }
vino-entity = { path = "../vino-entity", version = "0.9.0", optional = true }
vino-codec = { path = "../vino-codec", version = "0.9.0" }
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tracing = "0.1"

# raw
serde-value = { version = "0.7", optional = true }

# json
serde_json = { version = "1.0", optional = true }

# async
tokio = { version = "1", features = [], optional = true }
tokio-stream = { version = "0.1", optional = true }
parking_lot = { version = "0.12", optional = true }

[dev-dependencies]
test-log = "0.2.8"
anyhow = "1.0"
env_logger = "0.9"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
