[package]
name = "vino-codec"
version = "0.1.0"
edition = "2018"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = ["json", "messagepack"]
json = ["serde_json"]
messagepack = ["rmp-serde"]

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
rmp-serde = { version = "0.15.4", optional = true }
serde_json = { version = "1.0.65", optional = true }
thiserror = "1.0.25"
serde-value = "0.7.0"
