[package]
name = "vino-codec"
version = "0.1.0"
edition = "2018"
license = "BSD-3-Clause"
description = "JSON, Messagepack, & Raw serde value encoding/decoding library"
documentation = "https://docs.vino.dev"
keywords = ["serde", "vino", "codec", "json", "messagepack", "raw"]
categories = ["wasm"]
exclude = ["tests/*", ".github/*", ".gitignore"]

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["json", "messagepack"]
json = ["serde_json"]
messagepack = ["rmp-serde"]

[dependencies]
serde = { version = "1.0.118", features = ["derive"] }
rmp-serde = { version = "0.15.4", optional = true }
serde_json = { version = "1.0.65", optional = true }
thiserror = "1.0.25"
serde-value = "0.7.0"
